### ISSUE TITLE
Grieflog not working

### ISSUE THREAD

**Issue by Nomms** [blackwolf12333/GriefLog#14]
I honestly have no idea what's wrong. I threw Greiflog into my plugins folder and reloaded my server. No new 'greiflog' folder was created(if that was supposed to happen), the /glog commands don't work. When I do them in game it says /glog <options> <arguments>. It says the same thing in console if I use the /glog command too. And my console is a mess of glog errors. I've never used this plugin before, but I'd like to. Help would be appreciated. 

pastebin of server logs: http://pastebin.com/N2JSwks8
Server IP: 75.73.128.65

**Comment by Nomms** [comment]
I'm running the most recent development build.
SHA 6f2f08cdc2f67e42cc6ec1323565c5e07782154c
MD5 b869dd2222e822ace0c2bf1b828d8041

**Comment by blackwolf12333** [comment]
From what I can see from your server log you are not running any plugins at all, so you probably put it in the wrong folder.
Also, depending on how big your server is you might want to update to a bukkit beta build so you can use it with 1.7.9 clients.

**Comment by blackwolf12333** [comment]
Closing as invalid because no response after 11 days.
