### ISSUE TITLE
Failed to Handle Packet

### ISSUE THREAD

**Issue by delphicraft** [blackwolf12333/GriefLog#15]
Hello,

Getting this error in the log when running some GriefLog commands, including /glog and /glog tool

Failed to handle packet for /67.191.52.248:49731  (the port number changes)

Running on latest Dev build of Spigot.

Thank you!

**Comment by blackwolf12333** [comment]
If it is a development build of Spigot than I expect it is a problem with Spigot and not my plugin. Because my plugin doesn't do anything with packets.
